// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relationships.Data;

#nullable disable

namespace Relationships.Migrations
{
    [DbContext(typeof(ArtistsContext))]
    [Migration("20220709182845_OverrideConfigurationsWithFluentAPI")]
    partial class OverrideConfigurationsWithFluentAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Relationships.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("JuniorEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<long>("SeniorEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JuniorEmployeeId");

                    b.HasIndex("SeniorEmployeeId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Relationships.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Relationships.Album", b =>
                {
                    b.HasOne("Relationships.Employee", "JuniorEmployee")
                        .WithMany("JuniorEmployeeAlbums")
                        .HasForeignKey("JuniorEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relationships.Employee", "SeniorEmployee")
                        .WithMany("SeniorEmployeeAlbums")
                        .HasForeignKey("SeniorEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JuniorEmployee");

                    b.Navigation("SeniorEmployee");
                });

            modelBuilder.Entity("Relationships.Employee", b =>
                {
                    b.Navigation("JuniorEmployeeAlbums");

                    b.Navigation("SeniorEmployeeAlbums");
                });
#pragma warning restore 612, 618
        }
    }
}
