// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relationships.Data;

#nullable disable

namespace Relationships.Migrations
{
    [DbContext(typeof(ArtistsContext))]
    [Migration("20220712163742_OverrideConventionsUsingDataAnnotations")]
    partial class OverrideConventionsUsingDataAnnotations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("AlbumTag", b =>
                {
                    b.Property<long>("AlbID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlbID", "TID");

                    b.HasIndex("TID");

                    b.ToTable("AlbumTag");
                });

            modelBuilder.Entity("Relationships.Album", b =>
                {
                    b.Property<long>("AlbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("AlbID");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Relationships.Tag", b =>
                {
                    b.Property<long>("TID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("TID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AlbumTag", b =>
                {
                    b.HasOne("Relationships.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relationships.Tag", null)
                        .WithMany()
                        .HasForeignKey("TID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
